add serve command
aliyun/alibabacloud-resourcify-cli pull request #23
Opened 2020-10-26 09:28 UTC by night556

2020-10-26 09:38 UTC, JacksonTian commented on package.json
> +    "axios": "^0.20.0",
这个应该是 front 目录下的依赖。

2020-10-26 09:38 UTC, JacksonTian commented on package.json
> +    "eslint": "^6.8.0",
这个为啥改了

2020-10-26 09:38 UTC, night556 commented on package.json
> +    "axios": "^0.20.0",
好的 我修改一下

2020-10-26 09:38 UTC, JacksonTian requested changes
SMC

2020-10-27 01:44 UTC, JacksonTian approved these changes

2020-10-27 01:44 UTC, merged